# Generated by Django 5.1.7 on 2025-03-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.set')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
