# Generated by Django 5.1.7 on 2025-04-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='wanted_cards',
        ),
        migrations.AddField(
            model_name='trade',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='requested_cards',
            field=models.ManyToManyField(related_name='requested_in_trades', to='api.pokemoncard'),
        ),
    ]
