# Generated by Django 5.1.7 on 2025-04-15 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_trade_wanted_cards_trade_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='offered_cards',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='requested_cards',
        ),
        migrations.CreateModel(
            name='TradeOfferedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_items', to='api.trade')),
                ('user_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usercard')),
            ],
        ),
        migrations.CreateModel(
            name='TradeRequestedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pokemoncard')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', to='api.trade')),
            ],
        ),
    ]
