# Generated by Django 5.1.7 on 2025-04-15 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_trade_offered_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeofferedcard',
            name='user_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_trades', to='api.usercard'),
        ),
    ]
