# Generated by Django 5.1.7 on 2025-04-18 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_confirmed', models.BooleanField(default=False)),
                ('accepter_confirmed', models.BooleanField(default=False)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='api.trade')),
            ],
        ),
    ]
