# Generated by Django 5.1.7 on 2025-04-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_tradeconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('types', models.TextField(blank=True, null=True)),
                ('stats', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
