# Generated by Django 5.1.7 on 2025-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_guessmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guessmessage',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
