# Generated by Django 5.1.7 on 2025-04-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='offered_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='requested_coins',
            field=models.IntegerField(default=0),
        ),
    ]
