# Generated by Django 5.1.7 on 2025-05-20 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_trade_offered_coins_trade_requested_coins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_trades_as_accepter', to=settings.AUTH_USER_MODEL)),
                ('original_trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completed_trade', to='api.trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_trades_as_poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
