# Generated by Django 5.1.7 on 2025-05-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_completedtrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtrade',
            name='original_trade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_trade', to='api.trade'),
        ),
    ]
