# Generated by Django 5.1.7 on 2025-05-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_completedtrade_original_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtrade',
            name='original_trade',
        ),
        migrations.AddField(
            model_name='completedtrade',
            name='offered_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='completedtrade',
            name='offered_items_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedtrade',
            name='requested_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='completedtrade',
            name='requested_items_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
