# Generated by Django 5.1.7 on 2025-06-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_traderating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_guess_game_played',
            field=models.DateField(blank=True, null=True),
        ),
    ]
